
resources:
  repositories:
  - repository: repo-template
    type: github
    name: swo-agarcia/tf_lab
    endpoint: swo-agarcia
    ref: 'refs/heads/main'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - configuration
    - azure-pipelines.yaml
    exclude:
    - demo


  
variables:
- group: variables-demo-lab-aws-tf
- name: route
  value: $(System.DefaultWorkingDirectory)/configuration
- name: tfvars-file
  value: $(System.DefaultWorkingDirectory)/configuration/terraform.tfvars
  
jobs:

- template: templates/job-pipeline-template.yaml@repo-template  # Template reference
  parameters:
    action: deploy
    pool:
      vmImage: ubuntu-latest
